version: '3'

services:
  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=vile
  vile-server:
    image: vile:pgTxLog
    ports: 
      - "8080:8080"
    depends_on:
      - postgres
